/*
 * StatsWindow.java
 *
 * Copyright (C) 2011 Thomas Everingham
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * A copy of the GNU General Public License can be found in the file
 * LICENSE.txt provided with the source distribution of this program (see
 * the META-INF directory in the source jar). This license can also be
 * found on the GNU website at http://www.gnu.org/licenses/gpl.html.
 *
 * If you did not receive a copy of the GNU General Public License along
 * with this program, contact the lead developer, or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 *
 * If you find this program useful, please tell me about it! I would be delighted
 * to hear from you at tom.ingatan@gmail.com.
 */

package org.ingatan.component;

import org.ingatan.ThemeConstants;

/**
 * A statistics window with a sidebar and content pane. Allows the user to view
 * quiz history, as well as graphical statistics of quiz results for selected
 * libraries and flashcard type questions. Also holds the RewardsPane.
 *
 * @author Thomas Everingham
 * @version 1.0
 */
public class StatsWindow extends javax.swing.JFrame {

    /** The QuizHistoryPane displayed by this stats window */
    QuizHistoryPane historyPane = new QuizHistoryPane();

    /** The GropuStatsGraphPane displayed by this stats window */
    GroupStatsPane groupStatsPane = new GroupStatsPane();

    /** The LibraryStatsGraphPane displayed by this stats window */
    LibraryGraphsPane libStatsPane = new LibraryGraphsPane();

    /** Rewards pane displayed by this stats window */
    RewardsPane rewardsPane = new RewardsPane();

    /** Flashcard scatter pane displayed by this stats window */
    FlashcardScatterPane scatterPane = new FlashcardScatterPane();

    /** Creates new form StatsWindow */
    public StatsWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        horiz = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnQuizHistory = new javax.swing.JButton();
        btnLibraryGraphs = new javax.swing.JButton();
        btnFlashcardScatter = new javax.swing.JButton();
        btnGroupGraphs = new javax.swing.JButton();
        btnRewards = new javax.swing.JButton();
        contentPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        lblHeading.setText("Statistics and History");
        lblHeading.setFont(ThemeConstants.hugeFont.deriveFont(26.0f));
        lblHeading.setForeground(ThemeConstants.textColour);
        getContentPane().add(lblHeading);

        horiz.setAlignmentX(0.0F);
        horiz.setLayout(new javax.swing.BoxLayout(horiz, javax.swing.BoxLayout.LINE_AXIS));

        menuPanel.setAlignmentY(0.05F);
        menuPanel.setMaximumSize(new java.awt.Dimension(100, 200));
        menuPanel.setPreferredSize(new java.awt.Dimension(150, 450));
        menuPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 10));

        btnQuizHistory.setText("Quiz History");
        btnQuizHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizHistoryActionPerformed(evt);
            }
        });
        menuPanel.add(btnQuizHistory);

        btnLibraryGraphs.setText("Library Graphs");
        btnLibraryGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibraryGraphsActionPerformed(evt);
            }
        });
        menuPanel.add(btnLibraryGraphs);

        btnFlashcardScatter.setText("Flashcard Scatterplot");
        btnFlashcardScatter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlashcardScatterActionPerformed(evt);
            }
        });
        menuPanel.add(btnFlashcardScatter);

        btnGroupGraphs.setText("Group Statistics");
        btnGroupGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupGraphsActionPerformed(evt);
            }
        });
        menuPanel.add(btnGroupGraphs);

        btnRewards.setText("Rewards");
        btnRewards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRewardsActionPerformed(evt);
            }
        });
        menuPanel.add(btnRewards);

        horiz.add(menuPanel);

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        horiz.add(contentPane);

        getContentPane().add(horiz);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLibraryGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibraryGraphsActionPerformed
        contentPane.remove(historyPane);
        contentPane.remove(groupStatsPane);
        contentPane.remove(rewardsPane);
        contentPane.remove(scatterPane);
        contentPane.add(libStatsPane);
        contentPane.validate();
        contentPane.repaint();
    }//GEN-LAST:event_btnLibraryGraphsActionPerformed

    private void btnQuizHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizHistoryActionPerformed
        contentPane.remove(libStatsPane);
        contentPane.remove(groupStatsPane);
        contentPane.remove(rewardsPane);
        contentPane.remove(scatterPane);
        contentPane.add(historyPane);
        contentPane.validate();
        contentPane.repaint();
    }//GEN-LAST:event_btnQuizHistoryActionPerformed

    private void btnGroupGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupGraphsActionPerformed
        contentPane.remove(libStatsPane);
        contentPane.remove(rewardsPane);
        contentPane.remove(historyPane);
        contentPane.remove(scatterPane);
        contentPane.add(groupStatsPane);
        contentPane.validate();
        contentPane.repaint();
    }//GEN-LAST:event_btnGroupGraphsActionPerformed

    private void btnRewardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRewardsActionPerformed
        contentPane.remove(libStatsPane);
        contentPane.remove(historyPane);
        contentPane.remove(groupStatsPane);
        contentPane.remove(scatterPane);
        contentPane.add(rewardsPane);
        contentPane.validate();
        contentPane.repaint();
    }//GEN-LAST:event_btnRewardsActionPerformed

    private void btnFlashcardScatterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlashcardScatterActionPerformed
        contentPane.remove(historyPane);
        contentPane.remove(groupStatsPane);
        contentPane.remove(rewardsPane);
        contentPane.remove(libStatsPane);
        contentPane.add(scatterPane);
        contentPane.validate();
        contentPane.repaint();
    }//GEN-LAST:event_btnFlashcardScatterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlashcardScatter;
    private javax.swing.JButton btnGroupGraphs;
    private javax.swing.JButton btnLibraryGraphs;
    private javax.swing.JButton btnQuizHistory;
    private javax.swing.JButton btnRewards;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel horiz;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables

}
